# Generated by Django 4.2.7 on 2023-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personalinfo",
            options={
                "verbose_name": "1. Personal Info",
                "verbose_name_plural": "1. Personal Info",
            },
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="is_created",
            field=models.BooleanField(default=False),
        ),
    ]
