# Generated by Django 4.2.7 on 2023-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0002_alter_personalinfo_options_personalinfo_is_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="original_image_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
