# Generated by Django 4.2.7 on 2023-11-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0003_personalinfo_original_image_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="original_image_name",
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
