# Generated by Django 4.2.7 on 2023-11-28 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0004_remove_personalinfo_original_image_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="is_created",
        ),
    ]
